### ISSUE TITLE
need to set -pgma clang -pgmc clang on mac

### ISSUE THREAD

**Issue by cartazio** [luite/hfsevents#8]
`
Building hfsevents-0.1.5...
Preprocessing library hfsevents-0.1.5...
[1 of 1] Compiling System.OSX.FSEvents ( System/OSX/FSEvents.hs, dist/build/System/OSX/FSEvents.o )
gcc-4.8: error: language objective-c not recognized
gcc-4.8: error: language objective-c not recognized
`
if i pass -pgmc clang -pgma clang things work out fine

**Comment by ocramz** [comment]
I just ran into this problem as well, when compiling the latest stack :  `stack upgrade --git` . Where should one supply those flags in this case

**Comment by cartazio** [comment]
I'm not sure if stack lets you specify per package configuration flags.  So
you may be shit out of luck.  Also why isn't your GHC using clang for both
cpp and c code and asm?

**Comment by ocramz** [comment]
I'd rather find my answers elsewhere than thinking of being "shit out of luck". Thank you

**Comment by luite** [comment]
I've been hesitant to patch this package, since the problem points to a GHC installation issue rather than a problem with the package itself. Instead of hardcoding a compiler program name in all packages that need to compile Objective C it's best to fix the the problem at its source.

GHC gets the underlying compiler commands to use from its settings file (you can find the location with `ghc --print-libdir` and dump the config with `ghc --info`. How did you install your GHC?

**Comment by cartazio** [comment]
Agreed. Your error indicates a misconfigured Mac install of ghc.  Could you
provide more information about your config?

**Comment by luite** [comment]
I think this has been fixed by GHC and/or cabal by now

(welcome to open a new issue if new workarounds are needed of course)
